### PR TITLE
Version bump (patch)

### PR DESCRIPTION
**Pull request by newlukai**
Would you please publish the latest changes (isPending from almost two years ago)? Would be great.

### CODE REVIEW

**Comment by gazal-k** [comment]
I haven't used this in a while. I was just looking at this repo, and there really hasn't been any release. I couldn't find it in npm registry either. Do you wish to work further on this repo? I wouldn't mind letting someone else more keen on this becoming the maintainer

**Comment by newlukai** [comment]
It's not that I have much time or intent to make a unicorn out of the project. I just would make it work as long as I use it. If that's fine for you I would take over the project.

**Comment by gazal-k** [comment]
You could have forked this any time. But I'm also inviting u to be a collaborator on this repo if u'd like

**Comment by newlukai** [comment]
Yes, I could have forked it. And yes, the npm yearch doesn't find 
wct-xunit in its search. But, it's there: 
https://www.npmjs.com/package/wct-xunit
And as long as there is npm package, I would like to use it. And support 
it.

I'm not experienced in npm package maintenance. Is there a chance you 
update the package (or give me some role on that package allowed to 
update it)?

**Comment by gazal-k** [comment]
Sorry for the delayed response.

Thank you for finding the package on npm :slightly_smiling_face: :+1: 
I've just published the new version.

I can also invite u as a maintainer on the npm package. Same username on npmjs?

**Comment by newlukai** [comment]
Never mind. Time is rare :)
Thanks for publishing the new version. And yes, just invite me, it's the same username.

**Pull request merged**
